name: jkd

on:
  workflow_dispatch:
  schedule:
    - cron: '0,30 23,0-15/1 * * *'
  watch:
    types: started
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【聚看点】'
        run: |
          node Task/jukan.js
        env:
          JKD_COOKIE: ${{ secrets.JKD_COOKIE }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
